# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/clojure:tools-deps-1.10.1.763

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
            - v6-dependencies-{{ checksum "deps.edn" }}
      - run: rm -rf ~/.gitconfig
      - run: clojure -P -M:test:runner:jar:deploy
      - save_cache:
          paths:
            - ~/.m2
          key: v6-dependencies-{{ checksum "deps.edn" }}

  test:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:tools-deps-1.10.1.739

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v6-dependencies-{{ checksum "deps.edn" }}

      - run: rm -rf ~/.gitconfig

      # run tests!
      - run: clojure -M:test:runner --reporter kaocha.report/documentation

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: logs

  deploy:
    docker:
      - image: circleci/clojure:tools-deps-1.10.1.739

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v6-dependencies-{{ checksum "deps.edn" }}

      - run: rm -rf ~/.gitconfig

      - run:
          command: |
            bin/depstar-jar
            bin/depstar-deploy
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
      - deploy:
          filters:
            branches:
              only: /main/
            tags:
              only: /^v.*/
          requires:
            - test
          context: clojars-deploy