name: Publish to Clojars

on:
  push:
    tags:
      v.*

jobs:

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
          check-latest: false

      - name: Configure Maven
        uses: actions/setup-java@v3
        with: # running setup-java again overwrites the settings.xml
          distribution: 'temurin'
          java-version: '11'
          server-id: clojars # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: CLOJARS_USERNAME # env variable for username in deploy
          server-password: CLOJARS_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG private key passphrase

      - name: Publish to Clojars
        run: bin/mvn-deploy
        env:
          CLOJARS_USERNAME: cddr
          CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
