name: Publish to Clojars

on:
  push:
    tags:
      v.*

jobs:

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.1
        with:
          cli: 1.10.3.1087
      - name: Unit Tests
        run: clj -X:deploy
